"""Interactive scaffolding for the tessera server configuration file.

The ``init-config`` command collects one or more OAuth servers, the token
store, and the service URL, then writes a ``servers.yml`` that reloads
cleanly through the loader. Secrets are only ever referenced (an environment
variable name or a file path); no secret value is prompted, written, or
displayed.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import typer
import yaml
from kstlib.ui import PanelManager

from tessera.config.loader import load_config, resolve_config_path
from tessera.config.models import DEFAULT_COLOR_INVALID, DEFAULT_COLOR_VALID, TesseraConfig

_panels = PanelManager()

_HEADER = (
    "# tessera configuration generated by 'tessera init-config'.\n"
    "# Secrets are referenced by environment variable or file path, never\n"
    "# stored here. Register the printed redirect URI at your OAuth provider.\n"
)


def _prompt_provider() -> dict[str, Any]:
    """Collect the provider block: an OIDC issuer or explicit endpoints."""
    if typer.confirm("Use OIDC discovery (an issuer URL)?", default=True):
        return {"issuer": typer.prompt("Issuer URL")}
    return {
        "authorization_endpoint": typer.prompt("Authorization endpoint URL"),
        "token_endpoint": typer.prompt("Token endpoint URL"),
    }


def _prompt_secret_reference() -> dict[str, str]:
    """Collect a client-secret reference; the secret value is never asked."""
    if typer.confirm("Reference the client secret by environment variable?", default=True):
        return {"client_secret_env": typer.prompt("Client secret env var name")}
    return {"client_secret_file": typer.prompt("Client secret file path")}


def _prompt_server() -> tuple[str, dict[str, Any]]:
    """Collect one server entry, returned as its (name, mapping) pair."""
    name = typer.prompt("Server name")
    label = typer.prompt("Button label", default=name)
    provider = _prompt_provider()
    client_id = typer.prompt("Client id")
    secret = _prompt_secret_reference()
    scopes = typer.prompt("Scopes (space separated)", default="openid").split()
    color_valid = typer.prompt("Button color when valid", default=DEFAULT_COLOR_VALID)
    color_invalid = typer.prompt("Button color when invalid", default=DEFAULT_COLOR_INVALID)
    auto_refresh = typer.confirm("Refresh tokens automatically?", default=True)
    entry: dict[str, Any] = {
        "provider": provider,
        "client_id": client_id,
        **secret,
        "scopes": scopes,
        "button": {
            "label": label,
            "color_valid": color_valid,
            "color_invalid": color_invalid,
        },
        "auto_refresh": auto_refresh,
    }
    return name, entry


def _collect_servers() -> dict[str, Any]:
    """Loop collecting servers until the operator declines to add another."""
    servers: dict[str, Any] = {}
    while True:
        name, entry = _prompt_server()
        servers[name] = entry
        if not typer.confirm("Add another server?", default=False):
            return servers


def _prompt_key_reference() -> dict[str, str]:
    """Collect the store key reference (env, file, or SOPS), never the value."""
    kind = typer.prompt("Encryption key reference [env/file/sops]", default="env")
    if kind == "file":
        return {"key_file": typer.prompt("Key file path")}
    if kind == "sops":
        return {"key_sops": typer.prompt("SOPS file path")}
    return {"key_env": typer.prompt("Key env var name")}


def _prompt_store() -> dict[str, Any]:
    """Collect the token store: a database path and one key reference."""
    db_location = typer.prompt("Token store database path")
    return {"db_location": db_location, **_prompt_key_reference()}


def _run_wizard() -> dict[str, Any]:
    """Drive the full interactive wizard and return the config mapping."""
    servers = _collect_servers()
    store = _prompt_store()
    service = {"public_url": typer.prompt("Hub public URL")}
    return {"servers": servers, "store": store, "service": service}


def _example_template() -> dict[str, Any]:
    """Return a valid, ready-to-edit example configuration mapping."""
    return {
        "servers": {
            "demo": {
                "provider": {"issuer": "https://idp.example.com/realms/demo"},
                "client_id": "tessera-demo-client",
                "client_secret_env": "TESSERA_CLIENT_SECRET",
                "scopes": ["openid", "profile", "offline_access"],
                "button": {
                    "label": "Demo",
                    "color_valid": DEFAULT_COLOR_VALID,
                    "color_invalid": DEFAULT_COLOR_INVALID,
                },
                "auto_refresh": True,
            }
        },
        "store": {
            "db_location": "~/.config/tessera/tokens.db",
            "key_env": "TESSERA_DB_KEY",
        },
        "service": {"public_url": "https://hub.example.org"},
    }


def _write_config(data: dict[str, Any], target: Path, *, force: bool) -> None:
    """Write the configuration mapping, refusing to clobber without consent."""
    if target.exists() and not force:
        typer.confirm(f"{target} already exists, overwrite it?", abort=True)
    target.parent.mkdir(parents=True, exist_ok=True)
    body = _HEADER + yaml.safe_dump(data, sort_keys=False, default_flow_style=False)
    target.write_text(body, encoding="utf-8")


def _show_result(target: Path, config: TesseraConfig) -> None:
    """Show where the file went and the redirect URI to register."""
    _panels.print_panel(
        "success",
        payload={
            "Written": str(target),
            "Servers": ", ".join(config.server_names),
            "Redirect URI": config.service.redirect_uri,
        },
    )


def run(*, raw: bool, output: Path | None, force: bool) -> None:
    """Scaffold the configuration file, then validate it and show the result.

    Args:
        raw: When True, write a valid example template without prompting.
        output: Explicit target path; defaults to the loader cascade location.
        force: When True, overwrite an existing file without confirmation.
    """
    target = resolve_config_path(output)
    data = _example_template() if raw else _run_wizard()
    _write_config(data, target, force=force)
    config = load_config(target)
    _show_result(target, config)
